import { BaseClient } from '../client/base';
import { GeniSpaceConfig } from '../types';
/** Row from `GET /datasources` list (team-scoped). */
export interface DataSourceListItem {
    id: string;
    identifier?: string | null;
    name?: string | null;
    description?: string | null;
    operationType?: string | null;
    status?: string | null;
    databaseId?: string | null;
    sqlStatement?: string | null;
    metadata?: Record<string, unknown> | null;
    [key: string]: unknown;
}
export interface DataSourceListPagination {
    page: number;
    limit: number;
    total?: number;
    totalPages?: number;
}
/** Payload returned inside `data` for `GET /datasources/:id/data` (READ). */
export interface DataSourceReadPayload {
    data: Record<string, unknown>[];
    metadata?: {
        operationType?: string;
        columns?: string[];
        fields?: unknown[];
        rowCount?: number;
        executionTime?: number;
        [key: string]: unknown;
    };
    pagination?: {
        total?: number;
        page?: number;
        limit?: number;
        totalPages?: number;
        [key: string]: unknown;
    };
}
export interface GenerateOutputSchemaOptions {
    parameters?: Record<string, string | number | boolean | undefined>;
    strict?: boolean;
    save?: boolean;
    seed?: string;
    baseDate?: string;
}
export interface GenerateOutputSchemaResult {
    outputSchema: Record<string, unknown>;
    operationType?: string;
    columns?: string[];
    fieldCount?: number;
    usedParameters?: Record<string, unknown>;
    autoGeneratedParameters?: string[];
    missingParameters?: string[];
    warnings?: string[];
    saved?: boolean;
    lastUpdated?: string;
}
/**
 * Team SQL DataSources (`/datasources`); requires `team.datasource.read` for list/query.
 */
export declare class DataSources extends BaseClient {
    constructor(config: GeniSpaceConfig);
    /**
     * Paginated catalog; omit databaseId to search across the team's datasources.
     */
    listDataSources(params?: {
        page?: number;
        limit?: number;
        search?: string;
        databaseId?: string;
        status?: 'ACTIVE' | 'INACTIVE' | 'ERROR';
    }): Promise<{
        items: DataSourceListItem[];
        pagination: DataSourceListPagination;
    }>;
    /**
     * READ datasource proxy (`queryData`): extra keys become SQL parameter bindings when the datasource defines `{{param}}` placeholders.
     */
    queryDataSourceRead(datasourceId: string, params?: Record<string, string | number | boolean | undefined> & {
        page?: number;
        limit?: number;
    }): Promise<DataSourceReadPayload>;
    /**
     * Generate and optionally save datasource OutputSchema using server-side synthetic values for missing SQL parameters.
     */
    generateOutputSchema(datasourceId: string, options?: GenerateOutputSchemaOptions): Promise<GenerateOutputSchemaResult>;
}
